#!/usr/bin/env python3
"""Generate the binary .ofp test fixtures from the canonical empty fixture.

The .ofp container is CBOR-encoded JSON (see src/Format/Project.cpp). cbor2 round-trips the whole
document — including the axis `actions`, which are stored as CBOR byte strings — so we decode the
existing basic.ofp, mutate it, and re-encode, preserving the exact axis layout / simulator
positions / version the C++ writer produced.

Produces two fixtures:

  basic.ofp        — the shared fixture every UI test loads (tests/helpers/TestState.h::loadFixture).
                     Many suites assume its axes/bookmarks/chapters/regions are EMPTY (suite_undo,
                     suite_videocontrols, suite_bandbar, suite_timeline), so we only fill the
                     `metadata` block here — no suite asserts on it. Gives the metadata-editor UI
                     test and the ofp metadata round-trip something concrete to verify.

  roundtrip.ofp    — a dedicated fixture with L0 actions whose timestamps exercise the
                     seconds<->milliseconds conversion (notably a sub-millisecond value that must
                     truncate, not round). Kept separate from basic.ofp precisely so it can carry
                     actions without breaking the empty-baseline suites. Paired with
                     roundtrip.expected.funscript for the action-serialization round-trip test.

Action blob layout (must match actionsToBlob/actionsFromBlob in src/Format/Project.cpp):
  raw      = per action: float64 LE (at_seconds * 1000) ++ uint8 pos          (9 bytes each)
  blob     = uint32 LE (len(raw)) ++ zlib(raw)                                (miniz = zlib format)

Keep the constants below in sync with the expected values hard-coded in the C++ tests:
  tests/services/test_project_metadata.cpp   (ofp metadata load + save/reload round-trip)
  tests/services/test_project_manager.cpp    (roundtrip.ofp action + timestamp round-trip)
  tests/format/test_funscript.cpp            (sub-ms truncation)
  tests/ui/suite_metadata.cpp                (metadata editor UI test)

Usage:  python tools/gen_test_fixtures.py
Requires: pip install cbor2
"""

import json
import pathlib
import struct
import sys
import zlib

try:
    import cbor2
except ImportError:
    sys.exit("cbor2 not installed — run: pip install cbor2")

FIXTURES = pathlib.Path(__file__).resolve().parent.parent / "tests" / "fixtures"
BASIC = FIXTURES / "basic.ofp"
ROUNDTRIP = FIXTURES / "roundtrip.ofp"
ROUNDTRIP_EXPECTED = FIXTURES / "roundtrip.expected.funscript"

# Field names match FunscriptMetadata's JSON keys (src/Core/FunscriptMetadata.cpp); note the
# camelCase URL keys (scriptUrl/videoUrl) the .ofp format uses.
FIXTURE_METADATA = {
    "title": "Fixture Project",
    "creator": "OFS Test Suite",
    "scriptUrl": "https://example.com/script.funscript",
    "videoUrl": "https://example.com/video.mp4",
    "description": "Populated metadata fixture for round-trip tests.",
    "notes": "Generated by tools/gen_test_fixtures.py",
    "tags": ["alpha", "beta", "gamma"],
    "performers": ["Performer One", "Performer Two"],
    "license": "Free",
}

# (at_seconds, pos). 3.4567s is the key case: *1000 = 3456.7, which must ROUND to 3457 ms on
# funscript export (std::llround), not truncate to 3456. The rest are exact-at-ms values.
ROUNDTRIP_ACTIONS = [
    (0.5, 0),
    (1.0, 100),
    (2.75, 50),
    (3.4567, 30),
    (10.0, 0),
]


def actions_to_blob(actions):
    """Encode (at_seconds, pos) pairs exactly as src/Format/Project.cpp::actionsToBlob does."""
    raw = b"".join(struct.pack("<dB", at * 1000.0, pos) for at, pos in actions)
    return struct.pack("<I", len(raw)) + zlib.compress(raw)


def expected_funscript_ms(at_seconds):
    """Mirror the C++ export std::llround(at * 1000.0) — round to nearest ms (half away from zero)."""
    return int(at_seconds * 1000.0 + 0.5)  # at_seconds is non-negative for all fixture actions


def main():
    if not BASIC.exists():
        sys.exit(f"fixture not found: {BASIC}")

    # ── basic.ofp: metadata only, axes left untouched (empty) ────────────────────────────────
    project = cbor2.loads(BASIC.read_bytes())
    project["metadata"] = FIXTURE_METADATA
    BASIC.write_bytes(cbor2.dumps(project))
    print(f"updated {BASIC.name}: metadata title={FIXTURE_METADATA['title']!r}")

    # ── roundtrip.ofp: clone basic.ofp, give L0 the rounding-sensitive actions ────────────────
    rt = cbor2.loads(BASIC.read_bytes())
    l0 = next(ax for ax in rt["scriptAxes"] if ax["role"] == "L0")
    l0["actions"] = actions_to_blob(ROUNDTRIP_ACTIONS)
    ROUNDTRIP.write_bytes(cbor2.dumps(rt))
    print(f"wrote   {ROUNDTRIP.name}: L0 has {len(ROUNDTRIP_ACTIONS)} actions")

    # ── roundtrip.expected.funscript: the truncated-ms form L0 should export to ───────────────
    expected = {
        "actions": [
            {"at": expected_funscript_ms(at), "pos": pos} for at, pos in ROUNDTRIP_ACTIONS
        ]
    }
    ROUNDTRIP_EXPECTED.write_text(json.dumps(expected, indent=4) + "\n", encoding="utf-8")
    print(
        f"wrote   {ROUNDTRIP_EXPECTED.name}: ms="
        f"{[a['at'] for a in expected['actions']]}"
    )


if __name__ == "__main__":
    main()
