# Generates a C++ header of SHA-256 hashes baked into the app at build time, for two trust checks:
#
#   kFirstPartyPlugins  — shipped plugins (<PLUGIN_ROOT>/<name>/<name>.dll). PluginManager loads a
#                         matching one without the third-party consent prompt; a DLL that merely
#                         borrows the name (no match) still prompts.
#   kManagedAssemblies  — managed host infrastructure (<MANAGED_ROOT>/<name>.dll: Ofs.Api,
#                         Ofs.PluginHost, Ofs.ScriptHost). These run all plugin/script code, so a
#                         mismatch is a hard load failure (no prompt).
#
# Run twice: once at configure time (a baseline so the header always exists for compilation), and
# again as a build step after the DLLs are built (the authoritative hashes). Rewrites the header only
# when its content changes, so it never forces a needless recompile of dependents.
#
# Args (passed via -D on the `cmake -P` command line):
#   OUT_HEADER    absolute path of the header to (re)generate
#   PLUGIN_ROOT   directory holding <name>/<name>.dll for each first-party plugin
#   FIRST_PARTY   ;-separated list of first-party plugin names
#   MANAGED_ROOT  directory holding <name>.dll for each managed assembly
#   MANAGED       ;-separated list of managed assembly names

if (NOT DEFINED OUT_HEADER OR NOT DEFINED PLUGIN_ROOT OR NOT DEFINED FIRST_PARTY
        OR NOT DEFINED MANAGED_ROOT OR NOT DEFINED MANAGED)
    message(FATAL_ERROR "GenBakedHashes: OUT_HEADER, PLUGIN_ROOT, FIRST_PARTY, MANAGED_ROOT and MANAGED are required")
endif ()

# Build the brace-init entries for one {name -> sha256} table. The DLL is absent on a clean configure
# or a dotnet-less build; an empty hash means "no match" on the C++ side, so such a build falls back
# to the normal behaviour (prompt for plugins / skip the check for managed assemblies).
function(_emit_entries OUT_VAR ROOT NAMES LAYOUT)
    set(_acc "")
    foreach (_name IN LISTS NAMES)
        if (LAYOUT STREQUAL "subdir")
            set(_dll "${ROOT}/${_name}/${_name}.dll")
        else ()
            set(_dll "${ROOT}/${_name}.dll")
        endif ()
        set(_hash "")
        if (EXISTS "${_dll}")
            file(SHA256 "${_dll}" _hash)
        endif ()
        string(APPEND _acc "    {\"${_name}\", \"${_hash}\"},\n")
    endforeach ()
    set(${OUT_VAR} "${_acc}" PARENT_SCOPE)
endfunction()

_emit_entries(_fp "${PLUGIN_ROOT}" "${FIRST_PARTY}" "subdir")
_emit_entries(_mg "${MANAGED_ROOT}" "${MANAGED}" "flat")
list(LENGTH FIRST_PARTY _fp_count)
list(LENGTH MANAGED _mg_count)

set(_content "#pragma once
// AUTO-GENERATED by cmake/GenBakedHashes.cmake — do not edit.
// SHA-256 (lowercase hex) of the DLLs this build produced. An empty hash means the DLL was absent
// when generated and is treated as no match.
#include <array>
#include <string_view>

namespace ofs::generated {

struct BakedHash {
    std::string_view name;
    std::string_view sha256;
};

// Shipped plugins: auto-trusted by PluginManager when name+bytes match.
inline constexpr std::array<BakedHash, ${_fp_count}> kFirstPartyPlugins = {{
${_fp}}};

// Managed host infrastructure: a mismatch is a hard load failure (no prompt).
inline constexpr std::array<BakedHash, ${_mg_count}> kManagedAssemblies = {{
${_mg}}};

} // namespace ofs::generated
")

# Avoid rewriting (and so recompiling every dependent) when nothing changed.
set(_old "")
if (EXISTS "${OUT_HEADER}")
    file(READ "${OUT_HEADER}" _old)
endif ()
if (NOT _old STREQUAL _content)
    file(WRITE "${OUT_HEADER}" "${_content}")
endif ()
