# Generates a C++ header carrying the build's git identity — the commit hash (long and short) and the
# nearest tag — compiled into the binary so the running app can report exactly which revision it was
# built from.
#
# Run at configure time (a baseline so the header always exists) and on EVERY build (a custom target,
# not a file rule, because the checked-out commit can change without a reconfigure). Rewrites the
# header only when its content changes, so dependents recompile only when the revision actually moved.
#
# Args (passed via -D on the `cmake -P` command line):
#   OUT_HEADER      absolute path of the header to (re)generate
#   GIT_EXECUTABLE  path to git; empty/unset → all fields blank (built outside a checkout / no git)
#   WORK_DIR        repository working directory to query

if (NOT DEFINED OUT_HEADER OR NOT DEFINED WORK_DIR)
    message(FATAL_ERROR "GenBuildInfo: OUT_HEADER and WORK_DIR are required")
endif ()

set(_commit_long "")
set(_commit_short "")
set(_tag "")

# ERROR_QUIET + no result check: a missing git, a non-repo dir, or a tag-less history all leave the
# corresponding field empty, which the C++ side renders as "unknown" rather than failing the build.
if (DEFINED GIT_EXECUTABLE AND NOT GIT_EXECUTABLE STREQUAL "")
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${WORK_DIR}" rev-parse HEAD
            OUTPUT_VARIABLE _commit_long OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${WORK_DIR}" rev-parse --short HEAD
            OUTPUT_VARIABLE _commit_short OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    # --tags counts lightweight tags too; --dirty marks a tag with uncommitted changes. A history with
    # no tags makes this return non-zero, leaving _tag empty (intentional).
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${WORK_DIR}" describe --tags --dirty
            OUTPUT_VARIABLE _tag OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
endif ()

set(_content "#pragma once
// AUTO-GENERATED by cmake/GenBuildInfo.cmake — do not edit.
// Git identity of this build. Fields are empty when built outside a git checkout or without git.
#include <string_view>

namespace ofs::generated {

inline constexpr std::string_view kGitCommitLong  = \"${_commit_long}\";
inline constexpr std::string_view kGitCommitShort = \"${_commit_short}\";
inline constexpr std::string_view kGitTag         = \"${_tag}\"; // git describe --tags --dirty

} // namespace ofs::generated
")

# Avoid rewriting (and so recompiling every dependent) when the revision is unchanged.
set(_old "")
if (EXISTS "${OUT_HEADER}")
    file(READ "${OUT_HEADER}" _old)
endif ()
if (NOT _old STREQUAL _content)
    file(WRITE "${OUT_HEADER}" "${_content}")
endif ()
